  Fix SkyframeBuilder's error handling, and change the contract of EvaluationResult to return true for hasError() iff errorMap is non-empty or there is a catastrophe.  There was no good reason for the previous behavior of saying hasError even if there was a transitive recovered-from error, since callers shouldn't care. This was a latent bug that was only benign since none of the consumers of hasError were invoking Skyframe with recoverable SkyFunctions.  Also add an EvaluationResultSubject so that tests can more fluently assert things about EvaluationResult objects going forward.  -- MOS_MIGRATED_REVID=113192415  