  Interrupt the current thread on catching InterruptedExcepted in the test runner.  Summary: ProcessExecutor catches an InterruptedException to kill the child process, but since the exception was swallowed earlier, that catch/finally block would never run leaving zombie child processes behind. This explains why buck test --debug after interrupting an earlier buck test --debug invocation would not be able to bind to port 5005.  Test Plan: With buckd on, buck test javatests/com/facebook/cache:cache --debug Wait for the junit process to start and then Ctrl+C run buck test --debug again and verify that it works.  