  Don't trace debugger internals in Python 3.  