  fixed  AssertionError: Already disposed in PythonPathCache.<init> (61) (fast open/close project)  