  fixed PY-3560 utrunner.py throws exeption when runnins over python nose library  