 Fixed bug on tx.rollback(). Now can be called.  